@echo off
echo Running NASM...
nasm -f win32 average_filter.asm

echo Compiling app.c...
gcc -c app.c -o app.obj -m32 -std=c99

echo Linking app...
gcc app.c average_filter.obj -o app.exe -m32 -std=c99

echo Running app.exe...
.\app.exe
